-- Shared settings module
-- Initialized by KingCreoo on 7/18/2024

-- Define module
_Settings = {}

-- Module variables
_Settings.Version = "0.1"

_Settings.StandardData = {
    ["leaderstats"] = {
        ["Credits"] = 100
    },
    ["Version"] = _Settings.Version
}

_Settings.LevelData = {
    ["World1Level1"] = {
        ["StartingHorde"] = {
        [1] = 1,
        [2] = 1,
        [3] = 0,
        [4] = 0,
        [5] = 0,
        [6] = 0,
        [7] = 0,
        [8] = 0,
        [9] = 0,
        [10] = 0,
        [11] = 0,
        [12] = 0,
        [13] = 0,
        [14] = 0,
        [15] = 0,
        [16] = 0,
        [17] = 0,
        [18] = 0,
        [19] = 0,
        [20] = 0,
        [21] = 0,
        [22] = 0,
        [23] = 0,
        [24] = 0
        },
        ["Speed"] = 4
    },
    ["World1Level2"] = {
        ["StartingHorde"] = {
        [1] = 1,
        [2] = 1,
        [3] = 0,
        [4] = 0,
        [5] = 0,
        [6] = 0,
        [7] = 0,
        [8] = 0,
        [9] = 0,
        [10] = 0,
        [11] = 0,
        [12] = 0,
        [13] = 0,
        [14] = 0,
        [15] = 0,
        [16] = 0,
        [17] = 0,
        [18] = 0,
        [19] = 0,
        [20] = 0,
        [21] = 0,
        [22] = 0,
        [23] = 0,
        [24] = 0
        },
        ["Speed"] = 4
    },
    ["World1Level3"] = {
        ["StartingHorde"] = {
        [1] = 1,
        [2] = 1,
        [3] = 0,
        [4] = 0,
        [5] = 0,
        [6] = 0,
        [7] = 0,
        [8] = 0,
        [9] = 0,
        [10] = 0,
        [11] = 0,
        [12] = 0,
        [13] = 0,
        [14] = 0,
        [15] = 0,
        [16] = 0,
        [17] = 0,
        [18] = 0,
        [19] = 0,
        [20] = 0,
        [21] = 0,
        [22] = 0,
        [23] = 0,
        [24] = 0
        },
        ["Speed"] = 4
    }
}

-- Return module
return _Settings